apiVersion: v1
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "pods" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_phase"]
        target_label  = "pod_phase"
      }
      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name"]
        separator     = "/"
        target_label  = "job"
      }
    }

    prometheus.scrape "pods" {
      targets    = discovery.relabel.pods.output
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-nginx.mimir.svc.cluster.local/api/v1/push"
      }
    }
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy-metrics

# The following labels are included for discovered Pods:

    # __meta_kubernetes_namespace: The namespace of the Pod object.
    #__meta_kubernetes_pod_annotation_<annotationname>: Each annotation from the Pod object.
    #__meta_kubernetes_pod_annotationpresent_<annotationname>: true for each annotation from the Pod object.
    #__meta_kubernetes_pod_container_id: ID of the container the target address points to. The ID is in the form <type>://<container_id>.
    #__meta_kubernetes_pod_container_image: The image the container is using.
    #__meta_kubernetes_pod_container_init: true if the container is an InitContainer.
    #__meta_kubernetes_pod_container_name: Name of the container the target address points to.
    #__meta_kubernetes_pod_container_port_name: Name of the container port.
    #__meta_kubernetes_pod_container_port_number: Number of the container port.
    #__meta_kubernetes_pod_container_port_protocol: Protocol of the container port.
    #__meta_kubernetes_pod_controller_kind: Object kind of the Pod controller.
    #__meta_kubernetes_pod_controller_name: Name of the Pod controller.
    #__meta_kubernetes_pod_host_ip: The current host IP of the Pod object.
    #__meta_kubernetes_pod_ip: The Pod IP of the Pod object.
    #__meta_kubernetes_pod_label_<labelname>: Each label from the Pod object.
    #__meta_kubernetes_pod_labelpresent_<labelname>: true for each label from the Pod object.
    #__meta_kubernetes_pod_name: The name of the Pod object.
    #__meta_kubernetes_pod_node_name: The name of the node the Pod is scheduled onto.
    #__meta_kubernetes_pod_phase: Set to Pending, Running, Succeeded, Failed or Unknown in the lifecycle.
    #__meta_kubernetes_pod_ready: Set to true or false for the Pod’s ready state.
    #__meta_kubernetes_pod_uid: The UID of the Pod object.
